CREATE TABLE SALES_MASTER(
  SALESMAN_NO VARCHAR2(6) PRIMARY KEY CHECK (SALESMAN_NO LIKE 'S%'),
  SALES_NAME VARCHAR2(20) NOT NULL,
  ADDRESS VARCHAR2(20) NOT NULL,
  CITY VARCHAR2(20),
  STATE VARCHAR2(20),
  PINCODE NUMBER(6),
  SAL_AMT NUMBER(8,2) NOT NULL CHECK(SAL_AMT > 0),
  Tgt_to_get NUMBER(6,2) NOT NULL CHECK(SAL_AMT > 0),
  Ytd_sales NUMBER(6,2) NOT NULL CHECK(SAL_AMT > 0),
  Remark VARCHAR2(30)
 );

INSERT INTO SALES_MASTER (SALESMAN_NO, SALES_NAME, ADDRESS, CITY, STATE, PINCODE, SAL_AMT, Tgt_to_get, Ytd_sales, Remark)
VALUES ('S500001', 'Kiran', 'A/14, Worli', 'Bombay', 'MAH', 400002, 3000, 100, 50, 'Good');

INSERT INTO SALES_MASTER (SALESMAN_NO, SALES_NAME, ADDRESS, CITY, STATE, PINCODE, SAL_AMT, Tgt_to_get, Ytd_sales, Remark)
VALUES ('S500002', 'Manish', '65, Nariman', 'Bombay', 'MAH', 400001, 3000, 200, 100, 'Good');

INSERT INTO SALES_MASTER (SALESMAN_NO, SALES_NAME, ADDRESS, CITY, STATE, PINCODE, SAL_AMT, Tgt_to_get, Ytd_sales, Remark)
VALUES ('S500003', 'Ravi', 'P-7, Bandra', 'Bombay', 'MAH', 400032, 3000, 200, 100, 'Good');

INSERT INTO SALES_MASTER (SALESMAN_NO, SALES_NAME, ADDRESS, CITY, STATE, PINCODE, SAL_AMT, Tgt_to_get, Ytd_sales, Remark)
VALUES ('S500004', 'Ashish', 'A/5 Juhu', 'Bombay', 'MAH', 400044, 3500, 200, 150, 'Good');

SELECT * FROM SALES_MASTER
